### ISSUE TITLE
Doesn't seem to convert links in the [hello][reference] style

### ISSUE THREAD

**Issue by Carpetsmoker** [2ion/pandoc-bbcode#1]
This markdown file:

```
Let’s see what [POSIX has to say about it][posix] (emphases mine):

[^1]: Linux users can use [`strace`][strace]. OpenBSD users [`ktrace`][ktrace].
[posix]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html
```

Produces this bbcode:

```
Let’s see what [POSIX has to say about it][posix] (emphases mine):[~/src/pandoc-bbcode]
```

Removing the `[^1] ... ` line fixes it (this is a Kramdown extension to enable footnotes)...

**Comment by 2ion** [comment]
With pandoc 1.12.4.2, the example you provided produces
```
Let’s see what [POSIX has to say about it][posix] (emphases mine):
```
The [reference] is being processed properly when you put separate the footnote and reference definition by a newline:
```
Let’s see what [POSIX has to say about it][posix] (emphases mine):

[^1]: Linux users can use [`strace`][strace]. OpenBSD users [`ktrace`][ktrace].

[posix]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html
```
result:
```
Let’s see what [url=http://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html]POSIX has to say about it[/url] (emphases mine):
```
(Picking up the footnote works by referencing it in the text, and they will be put at the bottom).

Pandoc 1.13.2 produces the same results; I am still unable to reproduce this linetail
```
[~/src/pandoc-bbcode]
```
What switches are you using? The invocation I used so far is just
```
pandoc -f markdown -t panbbcode.lua -o output.bbc input.mkd
```

**Comment by Carpetsmoker** [comment]
Thanks.

Adding a newline between the footnotes & references fixed it ;-) This isn't required for my markdown to HTML parser, but it is for pandoc apparently.
