### ISSUE TITLE
Thank you for this great BBCode writer!

### ISSUE THREAD

**Issue by pbek** [2ion/pandoc-bbcode#2]
Thank you for this great BBCode writer!
I'm using it in my script [selected-markdown-to-bbcode.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/selected-markdown-to-bbcode.qml) to convert markdown direktly in [QOwnNotes](http://www.qownnotes.org/)!

**Comment by 2ion** [comment]
Cool, thanks.
